import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { formatCurrency } from "@/lib/constants";
import type { MelioBillRow } from "@/lib/melio";

/**
 * One-page vendor bill PDF for Melio's @invoicesmelio.com capture inbox.
 * Melio extracts vendor name, amount, invoice #, and due date from the attachment.
 */
export async function generateMelioTherapistBillPdf(options: {
  bill: MelioBillRow;
  remittanceNumber: string;
  therapistName: string;
  practiceName?: string;
  lineItems?: Array<{ description: string; amount: number }>;
}): Promise<Uint8Array> {
  const practice = options.practiceName ?? "Grandview Counseling";
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const { height } = page.getSize();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const margin = 54;
  let y = height - margin;

  page.drawText("INVOICE", {
    x: margin,
    y,
    size: 20,
    font: fontBold,
    color: rgb(0, 0, 0),
  });
  y -= 28;

  page.drawText(practice, {
    x: margin,
    y,
    size: 12,
    font: fontBold,
    color: rgb(0.15, 0.15, 0.15),
  });
  y -= 36;

  const meta: Array<[string, string]> = [
    ["Bill to (vendor)", options.bill.companyName],
    ["Therapist", options.therapistName],
    ["Invoice #", options.bill.invoiceNumber],
    ["Due date", options.bill.dueDate],
    ["Amount due", formatCurrency(options.bill.amount)],
    ["L&I remittance #", options.remittanceNumber],
  ];

  for (const [label, value] of meta) {
    page.drawText(`${label}:`, {
      x: margin,
      y,
      size: 10,
      font: fontBold,
      color: rgb(0.25, 0.25, 0.25),
    });
    page.drawText(value, {
      x: margin + 130,
      y,
      size: 10,
      font,
      color: rgb(0, 0, 0),
    });
    y -= 18;
  }

  y -= 16;
  page.drawText("Description", {
    x: margin,
    y,
    size: 10,
    font: fontBold,
    color: rgb(0, 0, 0),
  });
  page.drawText("Amount", {
    x: margin + 400,
    y,
    size: 10,
    font: fontBold,
    color: rgb(0, 0, 0),
  });
  y -= 8;
  page.drawLine({
    start: { x: margin, y },
    end: { x: 612 - margin, y },
    thickness: 1,
    color: rgb(0.7, 0.7, 0.7),
  });
  y -= 18;

  const lines =
    options.lineItems && options.lineItems.length > 0
      ? options.lineItems
      : [
          {
            description:
              options.bill.note ??
              `Therapist pay — L&I remittance ${options.remittanceNumber}`,
            amount: options.bill.amount,
          },
        ];

  for (const line of lines.slice(0, 24)) {
    const desc =
      line.description.length > 70 ? `${line.description.slice(0, 67)}…` : line.description;
    page.drawText(desc, {
      x: margin,
      y,
      size: 9,
      font,
      color: rgb(0, 0, 0),
    });
    page.drawText(formatCurrency(line.amount), {
      x: margin + 400,
      y,
      size: 9,
      font,
      color: rgb(0, 0, 0),
    });
    y -= 16;
  }

  y -= 12;
  page.drawText(`Total due: ${formatCurrency(options.bill.amount)}`, {
    x: margin,
    y,
    size: 12,
    font: fontBold,
    color: rgb(0, 0, 0),
  });

  y -= 36;
  page.drawText(
    "Generated by Grandview Counseling portal for Melio bill capture. Pay via ACH in Melio.",
    {
      x: margin,
      y,
      size: 8,
      font,
      color: rgb(0.4, 0.4, 0.4),
    },
  );

  return doc.save();
}
