import Link from "next/link";
import { notFound } from "next/navigation";
import { getRealUserId, requireAdmin } from "@/auth";
import { AdminManageForm } from "@/components/portal/AdminManageForm";
import { ConfirmSubmitButton } from "@/components/portal/ConfirmSubmitButton";
import {
  portalButtonSecondaryClass,
  portalCardCompactClass,
} from "@/components/portal/ui";
import { deleteAdminAction, resetAdminPasswordAction } from "@/lib/portal-actions";
import { prisma } from "@/lib/prisma";

export default async function EditAdminPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ saved?: string; passwordReset?: string }>;
}) {
  const session = await requireAdmin();
  const currentUserId = getRealUserId(session);
  const { id } = await params;
  const { saved, passwordReset } = await searchParams;

  const admin = await prisma.user.findFirst({
    where: { id, role: "ADMIN" },
    select: {
      id: true,
      email: true,
      firstName: true,
      lastName: true,
      _count: { select: { billsGenerated: true } },
    },
  });
  if (!admin) notFound();

  const isYou = admin.id === currentUserId;
  const canDelete = !isYou && admin._count.billsGenerated === 0;

  return (
    <div className="space-y-6">
      {saved === "1" && (
        <p className="rounded-lg bg-primary/10 px-3 py-2 text-sm text-primary-dark">
          Admin saved.
        </p>
      )}
      {passwordReset === "1" && (
        <p className="rounded-lg bg-primary/10 px-3 py-2 text-sm text-primary-dark">
          Password reset. They must change it on next login.
        </p>
      )}

      <div>
        <Link href="/portal/admin/admins" className={`${portalButtonSecondaryClass} text-xs`}>
          ← Back to admins
        </Link>
        <h1 className="mt-3 font-serif text-2xl font-semibold text-primary-dark">
          {admin.lastName}, {admin.firstName}
          {isYou && <span className="ml-2 text-base font-normal text-muted">(you)</span>}
        </h1>
        <p className="mt-1 font-mono text-sm text-muted">{admin.email}</p>
      </div>

      <AdminManageForm admin={admin} />

      <section className={`${portalCardCompactClass} space-y-3`}>
        <h2 className="text-xs font-semibold uppercase tracking-wide text-muted">Reset password</h2>
        <p className="text-sm text-muted">
          Sets a new temporary password and emails it to the admin. They must change it on next login.
        </p>
        <form action={resetAdminPasswordAction} className="flex flex-wrap items-end gap-3">
          <input type="hidden" name="id" value={admin.id} />
          <button type="submit" className={portalButtonSecondaryClass}>
            Reset password
          </button>
        </form>
      </section>

      {!isYou && (
        <section className={`${portalCardCompactClass} space-y-3`}>
          <h2 className="text-xs font-semibold uppercase tracking-wide text-muted">Delete admin</h2>
          {canDelete ? (
            <>
              <p className="text-sm text-muted">
                Permanently removes this admin account. They will no longer be able to sign in.
              </p>
              <form action={deleteAdminAction}>
                <input type="hidden" name="id" value={admin.id} />
                <ConfirmSubmitButton
                  confirmMessage={`Delete admin ${admin.email}?`}
                  className="text-sm text-red-700 hover:underline"
                >
                  Delete admin
                </ConfirmSubmitButton>
              </form>
            </>
          ) : (
            <p className="text-sm text-muted">
              Cannot delete while {admin._count.billsGenerated} L&I bill(s) were generated by this
              account.
            </p>
          )}
        </section>
      )}
    </div>
  );
}
